### PR TITLE
Lap counter

### LINKED ISSUE #5: F23, F24 Lap timer and counter
Implement a lap timer that tracks how long the car did for every lap. 

The formula student 2020 rulebook writes:

> D 8.2.5 Starting - A go-signal from RES is used to indicate the approval to begin. Timing starts after the vehicle crosses the starting line.

Let's use the center point of the car as the measurement point for timing. So start and stop the timer when the car's center point crosses the start/finish line.

A time value for every lap must be recorded and shown on the heads up display.

A lap counter can be derived from the number of timed laps. This value must also be shown on the heads up display.

Transmitting the lap times and lapcounter to some place outside unreal engine is out of scope for this issue.

### PR DESCRIPTION
**Pull request by Riliano**
Adds an object to represent start/finish line and exports the time of each passed lap.
Closes #5

### CODE REVIEW

**Comment by Riliano** [comment]
It should ideally be on all maps, but for now I only modified MAP1

**Comment by SijmenHuizenga** [comment]
Screenshot from 2020-05-15 10-09-37
Is this normal?

**Comment by Riliano** [comment]
> Screenshot from 2020-05-15 10-09-37
> Is this normal?

welllll, kinda..
The spawn capsule is clipped into the ground, thats why the labes is there. But the actual car spawns a bit above the capsule (I'm sure you noticed how the car "drops" on startup) this just lowers it a bit, its not perfect but its less of a drop.

**Comment by SijmenHuizenga** [comment]
> welllll, kinda..
> The spawn capsule is clipped into the ground, thats why the labes is there. But the actual car spawns a bit above the capsule (I'm sure you noticed how the car "drops" on startup) this just lowers it a bit, its not perfect but its less of a drop.

Okey! Good to know :+1:

**Pull request merged**
