### PR TITLE
Add restart() function to reset the cones and the vehicle to their original starting state

### PR DESCRIPTION
**Pull request by mattbrth**
**I think AirSim was missing a function to reset the cones that's why I implemented this.**

Here is how it works:
RestartLevel() was a member of player_controller but I managed to access it from the WorldSim instance with the added function ASimModeBase::restart() in the SimModeBase.cpp module. 
I then connected this function to the RcpLibClient to be called by the python client.

### CODE REVIEW

**Comment by wouter-heerwegh** [comment]
Hi @MattBrth

Thanks for the implementation. I made some changes aswell to implement a ros1 service to call it, but I was not able to push these changes to this pull request. Could it be possible to enable edits by maintainers on this PR so I can add them here? Otherwise I will close this and open a new PR between a branch on this repo an the master branch.

I saw you added an acceleration map to the maps folder. Is this the standard Acceleration map that is provided within the simulator, or did you add one yourself?

**Comment by MattBrth** [comment]
I forgot to revert the map folder ... Unfortunately I don't have the box " Allow edits from maintainers." even when I try to recreate another one. Do you know why ?

**Comment by wouter-heerwegh** [comment]
Most likely because the repo is forked on your organization and I probably don't have rights to work on it

**Comment by MattBrth** [comment]
@wouter-heerwegh Ok so I should create a branch in this repo and open my PR in it ?

**Comment by MattBrth** [comment]
@wouter-heerwegh well i saw you already did it on your branch :)

**Comment by wouter-heerwegh** [comment]
@MattBrth yes, so we can close this one

**Pull request closed without merging**
